version: '3'

services:

  mms-config-server:
    container_name: 'mms-config-server'
    build: ./mms-config-server/
    ports:
      - 9090:9090
    networks: 
      - mms-network

  mms-eureka-server:
    container_name: 'mms-eureka-server'
    build: ./mms-eureka-server/
    depends_on: 
      - mms-config-server
    ports:
      - 8080:8080
    networks: 
      - mms-network

networks:
  mms-network: