server:
  port: ${PORT:9090}

spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:${HOME}/Documents/mastering-music-store}
          searchPaths: 'mms-config-files/{application}'