server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gbzarelli/mastering-music-store.git
          #uri: ${HOME}/Documents/mastering-music-store
          searchPaths: 'mms-config-files/{application}'